iframe/urls.py
from django.conf.urls import url

import iframe.views

urlpatterns = [
    url(r'^(?P<pk>\d+)', iframe.views.FrameView.as_view()),
    url(r'^add', iframe.views.add, name="add_new_frame"),
    url(r'^snippet/(?P<pk>\d+)', iframe.views.snippet, name="snippet"),
]

www/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from rest_framework import routers
from www.admin import markers_edit_site
from www import settings
from registration.forms import RegistrationFormUniqueEmail
from registration.backends.hmac.views import RegistrationView


import maps.views
import closet.views
import iframe.views
import www.views

router = routers.DefaultRouter()
router.register(r'markers', maps.views.MarkerViewSet)
router.register(r'categories', closet.views.CategoryViewSet)
router.register(r'subcategories', closet.views.SubcategoryViewSet)
router.register(r'iframes', iframe.views.IframeViewSet)

urlpatterns = [
    url(r'^$', www.views.index),
    url(r'^accounts/register/$',
        RegistrationView.as_view(
            form_class=RegistrationFormUniqueEmail
        ),
        name='registration_register',
    ),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^csv/import/select/category/$', maps.views.csv_import_choose_cat, name='csv_import'),
    url(r'^csv/import/category/(?P<cat_id>[0-9]+)', maps.views.csv_import_for_cat, name='csv_import_for_cat'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^marker-edit/login/$', auth.views.login),
    url(r'^marker-edit/', include(markers_edit_site.urls)),
    url(r'^api/', include(router.urls)),
    url(r'^frame/', include('iframe.urls')),
    url('^api/subcategories/(?P<subcategory_id>.+)/markers-2$',
        maps.serializers.MakersBySubCategoriesList.as_view()),
    url('^api/markers/(?P<marker_id>.+)/history$', maps.views.MarkerHistoryView.as_view(), name='markers-history'),
]

if settings.DEBUG:
    from django.contrib.staticfiles import views
    urlpatterns += [url(r'^static/(?P<path>.*)$', views.serve)]

closet/models.py
from django.db import models
from django.core.validators import RegexValidator


ColorValidator = RegexValidator(
    regex=r'^[A-Fa-f0-9]{6}$',
    message="Entrez une couleur valide (pas de '#' et 6 caractères)",
)


class Category(models.Model):
    name = models.CharField(blank=False, max_length=255)
    description = models.TextField(blank=True)
    color = models.CharField(blank=False, max_length=6, validators=[ColorValidator])
    order = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['order']


class Subcategory(models.Model):
    name = models.CharField(blank=False, max_length=255)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, null=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = "Sub-category"
        verbose_name_plural = "Sub-categories"

iframe/models.py
from django.contrib.gis.db import models
from django.core.validators import MaxValueValidator


class Map(models.Model):
    center = models.PointField(geography=True, blank=False)
    zoom = models.PositiveIntegerField(validators=[MaxValueValidator(18)])
    subcategories = models.ManyToManyField('closet.Subcategory', blank=True)

    @property
    def center_lat(self):
        return self.center.y

    @property
    def center_lon(self):
        return self.center.x

iframe/forms.py
from django import forms
from closet.models import Subcategory


class MapForm(forms.Form):
    latitude = forms.FloatField()
    longitude = forms.FloatField()
    zoom = forms.IntegerField()
    subcategories = forms.ModelMultipleChoiceField(
        queryset=Subcategory.objects.all(),
        required=False,
    )

maps/forms.py
from closet.models import Category, Subcategory
from django import forms
from django.core.exceptions import ValidationError

def validate_subcat(input):
    sub = input.split(",")
    # if len(sub) < 1:
    #     raise ValidationError(
    #        "Il faut au moins sélectionner une sous-catégorie")
    for cat in sub:
        if not cat.isnumeric():
            ValidationError("Catégorie invalide")

# TODELETE
class MarkerForm(forms.Form):
    name = forms.CharField(required=True)
    web = forms.URLField(required=False)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    lat = forms.FloatField(required=True)
    lon = forms.FloatField(required=True)
    description = forms.CharField(required=False)
    subcat = forms.CharField(validators=[validate_subcat])


class CSVImportChooseCatForm(forms.Form):
    """ Form to choose the category before uploading a csv file """
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), empty_label=None)


class CSVImportForCatForm(forms.Form):
    """ Form to import csv file into a subcategory. A category is given via
    the url """
    sub_category = forms.ModelMultipleChoiceField(queryset=Subcategory.objects.all())
    csv_file = forms.FileField()
    #  TODELETE csv_old = forms.CharField(required=True, widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        cat_id = kwargs.pop('cat_id')
        super(CSVImportForCatForm, self).__init__(*args, **kwargs)
        self.fields['sub_category'].queryset = Subcategory.objects.filter(
            category__id=cat_id)

iframe/views.py
from iframe.models import Map
from django.views.generic.detail import DetailView
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.gis.geos import Point
from django.core.urlresolvers import reverse

from iframe.serializers import MapSerializer
from rest_framework import viewsets
from iframe.forms import MapForm
from closet.models import Category


from django.views.decorators.clickjacking import xframe_options_exempt


class FrameView(DetailView):
    model = Map
    context_object_name = 'map'

    @xframe_options_exempt
    def get(self, request, *args, **kwargs):
        return super(DetailView, self).get(request, *args, **kwargs)


class IframeViewSet(viewsets.ModelViewSet):
    queryset = Map.objects.all()
    serializer_class = MapSerializer


def add(request):
    if request.method == 'POST':
        form = MapForm(request.POST)
        if form.is_valid():
            frame = Map.objects.create(
                zoom=form.cleaned_data['zoom'],
                center=Point(form.cleaned_data['longitude'], form.cleaned_data['latitude']),
            )
            frame.subcategories.add(*form.cleaned_data['subcategories'])
            return HttpResponseRedirect(reverse('snippet', args=[frame.id]))
    else:
        form = MapForm() # An unbound form

    return render(request, 'iframe/map_form.html', {
        'form': form,
        'categories': Category.objects.all(),
    })


def snippet(request, pk):
    return render(request, 'iframe/snippet.html', {
        'id': pk,
    })

maps/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from rest_framework import viewsets
from maps.serializers import MarkerSerializer
from django.views.decorators.csrf import csrf_exempt
from django.contrib.gis.geos import Point
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from maps.models import Marker
from closet.models import Subcategory, Category
import csv
from django.db import transaction
from maps.forms import CSVImportChooseCatForm, CSVImportForCatForm, MarkerForm
from io import TextIOWrapper
from rest_framework.views import APIView
from rest_framework.response import Response
import reversion


class MarkerViewSet(viewsets.ModelViewSet):
    queryset = Marker.objects \
        .prefetch_related('subcategories').filter(public=True)
    serializer_class = MarkerSerializer


class MarkerHistoryView(APIView):
    """
    View to list the history for a given marker.
    """
    def get(self, request, marker_id):
        """
        For a given marker list its history
        """
        marker = Marker.objects.get(pk=marker_id)
        return Response(marker.get_history_for_json())


@login_required
def csv_import_choose_cat(request):
    """
    View with a form to choose a category for importing a csv file
    """
    if request.method == 'POST':
        form = CSVImportChooseCatForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            return redirect('csv_import_for_cat', cat_id=data['category'].id)
        else:
            return render(request, 'maps/csv_import_form.html', {'form': form})
    else:
        form = CSVImportChooseCatForm()
        return render(request, 'maps/csv_import_form.html', {'form': form})

@login_required
def csv_import_for_cat(request, cat_id):
    """
    View whith a form to choose a subcategory and upload a csv file. The
    csv file contains new markers that will be added to the subcategory.

    :param cat_id: The id of the subcategories (chosen by the user at the
    previous step).
    """
    if request.method == 'POST':
        form = CSVImportForCatForm(request.POST, request.FILES, cat_id=cat_id)
        if form.is_valid():
            subcat_id = form.cleaned_data['sub_category']
            csvfile = None
            encodings = ['utf-8', 'windows-1250', 'windows-1252']
            for e in encodings:
                try:
                    request.FILES['csv_file'].file.seek(0)
                    request.FILES['csv_file'].file.read().decode(e)
                    request.FILES['csv_file'].file.seek(0)
                    csvfile = TextIOWrapper(
                        request.FILES['csv_file'].file, encoding=e)
                except UnicodeDecodeError:
                    # si pbm d'encodage la ligne
                    # request.FILES['csv_file'].file.read().decode(e)
                    # va lancer une exception -> on cherche un nouvel encodage
                    # print('got unicode error with %s , trying different encoding' % e)
                    pass
                else:
                    # l'encodage a ete trouve -> csvfile contient une bonne donnée
                    # print('opening the file with encoding:  %s ' % e)
                    break
            if csvfile:
                return import_csv(request, csvfile, subcat_id)
            else:
                return render(
                    request, 'www/basic_message.html', {
                        'message': 'Encodage non trouvé',
                        'message_type': 'alert',
                    })
        else:
            return render(request, 'maps/csv_import_form.html', {'form': form})
    else:
        form = CSVImportForCatForm(cat_id=cat_id)
        return render(request, 'maps/csv_import_form.html', {'form': form})


@transaction.non_atomic_requests  # either all the elements are imported in db
# either none of the elements are imported in db
def import_csv(request, csvfile, subcat_id):
    """
    Read the CSV file and load it in database
    """
    required_fields = ['name', 'lat', 'lon', 'address']
    optional_fields = ['comment', 'web', 'email', 'phone']

    dialect = csv.Sniffer().sniff(csvfile.read())
    csvfile.seek(0)
    reader = csv.reader(csvfile, dialect)

    lines = list(reader)
    header = lines.pop(0)

    points, error_message = get_and_check_csv_data(
        required_fields, optional_fields, header, lines)

    if points:
        for point in points:
            pos = Point(float(point['lon']), float(point['lat']))
            with reversion.create_revision():
                m = Marker.objects.create(
                    name=point['name'],
                    address=point['address'],
                    position=pos)

                for fo in optional_fields:
                    if fo in point:
                        setattr(m, fo, point[fo])

                m.subcategories.add(Subcategory.objects.get(pk=subcat_id))
                m.save()
                reversion.set_user(request.user)
                reversion.set_comment("Import form csv")
        message = 'Thanks a lot, the points were added to the map!'
        message_type = 'success'
    else:
        message = error_message
        message_type = 'alert'

    return render(
        request, 'www/basic_message.html', {
            'message': message,
            'message_type': message_type,
        })


def get_and_check_csv_data(
        required_fields, optional_fields, header_line, other_lines):
    """
    Return a list of dictionaries that represent each point to add. The key of
    the dictionary is the name of the parameter of the object Marker.

    :param required_fields: The name of the required fields
    :param optional_fields: The name of the optional fields
    :param header_line: The header lines get from csv.reader call
    :param other_lines: The other lines get from csv.reader call
    :returns: A tuple of 2 elements : the first element is the array list of
        dictionaries (if everithing went well), the second element is the
        error message.
    """
    mapping = {}
    header_uppercase = [h.upper() for h in header_line]

    # Check if the require fields are in the header
    for fn in required_fields:
        fn_upper = fn.upper()
        if fn_upper not in header_uppercase:
            return (None, '{} not in the header.'.format(fn))
        else:
            mapping[fn] = header_uppercase.index(fn_upper)

    # Add the optional fields
    for fn in optional_fields:
        fn_upper = fn.upper()
        if fn_upper in header_uppercase:
            mapping[fn] = header_uppercase.index(fn_upper)

    # Read the liens for each points
    points = []
    for line in other_lines:
        # Create a dictionary with the received data
        point = {}
        for field_name, pos in mapping.items():
            # Traiter ligne vide
            point[field_name] = line[pos]

        # Check if we have an empty line
        empty_line = True
        for fn in required_fields:
            if point[fn] != '':
                empty_line = False
                break

        if not empty_line:
            # Check if the the required_fields are completed
            for fn in required_fields:
                if point[fn] == '':
                    return (
                        None, 'One line has its field "{}" empty'.format(fn))

            point['lat'] = float(point['lat'])
            point['lon'] = float(point['lon'])

            # Check if lat / long is good
            if point['lat'] > 90 or point['lat'] < -90 or \
                    point['lon'] > 180 or point['lon'] < -180:
                return (
                    None, 'It is not possible to create the point {} \
with lat: {} and lon: {}'
                    .format(point['name'], point['lat'], point['lon']))
            points.append(point)

    return (points, None)

templates/iframe/base.html
{% load leaflet_tags %}


<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" >

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dewey maps</title>

        <link rel="stylesheet" href="/static/lib/foundation/css/normalize.css">
        <link rel="stylesheet" href="/static/lib/foundation/foundation.css">
        <link rel="stylesheet" href="/static/lib/qtip2/jquery.qtip.min.css">
        <link rel="stylesheet" href="/static/lib/leaflet/leaflet.css" />
    </head>
    <body>

    {% block "content" %}
    {% endblock %}

    <script src="/static/lib/foundation/js/vendor/modernizr.js"></script>
    <script src="/static/lib/leaflet/leaflet-src.js"></script>
    <script src="/static/lib/jquery/jquery.js"></script>
    <script src="/static/lib/foundation/foundation.js"></script>

    {% block scripts %}
    {% endblock %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-58277820-5', 'auto');
      ga('send', 'pageview');

    </script>
    </body>
</html>

templates/iframe/map_detail.html
<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" >

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="/static/lib/foundation/foundation.css">
  <link rel="stylesheet" href="/static/lib/leaflet/leaflet.css" />
  <link rel="stylesheet" href="/static/lib/font-awesome/css/font-awesome.min.css">
</head>
<body style="padding: 0; margin: 0" frame_id="{{map.id}}">
  <div id="map" style="width: 100%; height: 100vh">
  </div>

  <script data-main="/static/frame" src="/static/lib/requirejs/require.js"></script>
</body>

</html>

templates/iframe/map_form.html
{% extends "iframe/base.html" %}

{% block "content" %}
<div class="row">
    <div class="large-12 columns">
    <h1>Intégrez DeweyMaps à votre site</h1>
    </div>
</div>
    <form action="" method="POST">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="row">
            <div class="large-12 columns">
                <h3>Choisissez où centrer la carte</h3>
                <p>Déplacez la carte et zoomez comme vous voulez</p>
            </div>
            <div class="large-12 columns">
                <div id="map" style="height: 400px"></div>
                <br>
            </div>
            <div class="large-4 columns">
              <label>Latitude
                <input type="text" name="latitude" readonly />
              </label>
            </div>
            <div class="large-4 columns">
              <label>Longitude
                <input type="text" name="longitude" readonly />
              </label>
            </div>
            <div class="large-4 columns">
              <label>Zoom
                <input type="text" name="zoom" readonly />
              </label>
            </div>
            <div class="large-12 columns">
                <h3>Choisissez les catégories de points à afficher</h3>
            </div>
            {% for cat in categories %}
                <div class="large-4 columns">
                    <h5 style="background-color: #{{cat.color}}; padding: 0.2em"><i class="fi fi-folder"></i> {{cat.name}}</h5>
                    {% for subcat in cat.subcategory_set.all %}
                        <label style="padding-left: 1.5em">
                            <input type="checkbox" name="subcategories" value="{{subcat.id}}">
                            {{subcat.name}}
                        </label>

                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="large-12 columns">
                <input type="submit" value="Créer ma carte" class="button"/>
            </div>
        </div>
    </form>

{% endblock %}

{% block scripts %}
<script>
var map = L.map('map').setView([50.84, 4.36], 12);


L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'c4ptaincrunch.ka5engdh',
    accessToken: 'pk.eyJ1IjoiYzRwdGFpbmNydW5jaCIsImEiOiJUdWVRSENNIn0.qssi5TBLeBinBsXkZKiI6Q'
}).addTo(map);

var update = function(){
    pos = map.getCenter();
    $("input[name='latitude']").val(pos.lat);
    $("input[name='longitude']").val(pos.lng);
    $("input[name='zoom']").val(map.getZoom());
};

$( document ).ready(function() {
    update();
});

map.on('zoomend', function(e) {
    update();
});

map.on('dragend', function(e) {
    update();
});
</script>
{% endblock %}

templates/iframe/snippet.html
{% extends "iframe/base.html" %}

{% block "content" %}
    <div class="row">
        <div class="large-12 columns">
            <h1>Dewey Maps</h1>
            <h3>Voici le code à insérer dans votre page web</h3>
        </div>
        <div class="large-12 columns">
            <code>
{% filter force_escape|lower %}
<iframe src="http://maps.dewey.be/frame/{{id}}" style="width:100%; height:500px"></iframe>
{% endfilter %}
            </code>
        </div>
        <div class="large-12 columns">
            <br>
            <a href="/" class="button">Retour à Dewey Maps</a>
        </div>
    </div>
{% endblock %}